
server:
  port: 8889

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hejinzhao?useUnicode=true&characterEncoding=utf8
    password:
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver



  jpa:
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    database: 2

mybatis:
  type-aliases-package: cn.gson.hejinzhao.model.pojos
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    cache-enabled: true

